// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1QedKFvlM01HslAJtYj3QbemQyrIZmo',
    appId: '1:811582433570:web:92a56b487c4a8ef3ebdd7b',
    messagingSenderId: '811582433570',
    projectId: 'chat-app-1f4af',
    authDomain: 'chat-app-1f4af.firebaseapp.com',
    storageBucket: 'chat-app-1f4af.firebasestorage.app',
    measurementId: 'G-NDFBDS6752',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9aTC6W__WGWSWOvfcSqU2uGcVJ2ABsE',
    appId: '1:811582433570:android:59f7566e7300cfd6ebdd7b',
    messagingSenderId: '811582433570',
    projectId: 'chat-app-1f4af',
    storageBucket: 'chat-app-1f4af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDX63qPRFmW02aVBouie5s8Evp9q_tvU',
    appId: '1:811582433570:ios:2bc443978ec951f7ebdd7b',
    messagingSenderId: '811582433570',
    projectId: 'chat-app-1f4af',
    storageBucket: 'chat-app-1f4af.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDX63qPRFmW02aVBouie5s8Evp9q_tvU',
    appId: '1:811582433570:ios:2bc443978ec951f7ebdd7b',
    messagingSenderId: '811582433570',
    projectId: 'chat-app-1f4af',
    storageBucket: 'chat-app-1f4af.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF1QedKFvlM01HslAJtYj3QbemQyrIZmo',
    appId: '1:811582433570:web:28cdc36582001aadebdd7b',
    messagingSenderId: '811582433570',
    projectId: 'chat-app-1f4af',
    authDomain: 'chat-app-1f4af.firebaseapp.com',
    storageBucket: 'chat-app-1f4af.firebasestorage.app',
    measurementId: 'G-028LN5XN87',
  );
}
